name: evidence
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - gensim
  - ipykernel
  - jupyter
  - nbconvert
  - pandas
  - pip
  - tqdm
  - pip:
    - import-ipynb
    - smart-open
