version: '3'

services:

  server:
    build:
      context: ./ui
    entrypoint: ["./start.sh"]
    ports:
      - "8080:8080"
    volumes:
      - ./experiments/${EXPERIMENT}/model:/data:ro
      - ./experiments/${EXPERIMENT}/db:/db

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.6.1"
    environment:
      discovery.type: "single-node"
    expose:
      - "9200"

  indexer:
    build:
      context: ./ui/indexer
    depends_on:
      - "elasticsearch"
    command: ["/utils/wait-for-it.sh", "elasticsearch:9200",
      "--timeout=0",
      "--", "/utils/index.py",
      "data/model/vocabulary_ids.txt",
      "data/model/vocabulary_bow.txt",
      "elasticsearch"]
    volumes:
      - ./experiments/${EXPERIMENT}:/data:ro

  usercreator:
    build:
      context: ./ui/usercreator
    depends_on:
      - server
    entrypoint: ["/utils/wait-for-it.sh", "server:8080",
        "--timeout=0",
        "--",
        "/usr/bin/curl", "-X", "POST", "http://server:8080/users", "-d", "${WORKINGTITLECLOSEREADER_USER:-demo}"]
