version: '2'

services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["./evidence-gui", "-elastic", "http://elasticsearch:9200"]
    ports:
      - "8080:8080"

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.6.1"
    environment:
      discovery.type: "single-node"
    expose:
      - "9200"

  indexer:
    build:
      context: indexer
      dockerfile: Dockerfile
    depends_on:
      - "elasticsearch"
    command: ["/utils/wait-for-it.sh", "elasticsearch:9200", "--",
    "/utils/index.py", "elasticsearch"]
    volumes:
      - "$DATA:/data:ro"
