version: '3'

services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["./evidence-gui",
                 "-db", "/db/relevance.db",
                 "-doc2vec", "/data/doc2vec.csv",
                 "-elastic", "http://elasticsearch:9200"]
    ports:
      - "8080:8080"
    volumes:
      - "$DATA:/data:ro"
      - db-volume:/db

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.6.1"
    environment:
      discovery.type: "single-node"
    expose:
      - "9200"

  indexer:
    build:
      context: indexer
      dockerfile: Dockerfile
    depends_on:
      - "elasticsearch"
    command: ["/utils/wait-for-it.sh", "elasticsearch:9200",
      "--timeout=0",
      "--", "/utils/index.py", "elasticsearch"]
    volumes:
      - "$DATA:/data:ro"

volumes:
  db-volume:
