name: Test model generation

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker-compose --file generate-model.yml build generate-model
      - name: Prepare the test data
        run: |
          cd experiments
          mkdir -p test/corpus test/model
          cp -irv getuigenverhalen/corpus/GV_Zigma_koopvaardij_08_conversation_clipped test/corpus/
      - name: Generate the model
        run: |
          docker-compose --file generate-model.yml run --user $(id -u):$(id -g) generate-model
        env:
          EXPERIMENT: test
