name: Test model generation

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker build --tag doc2vec ./model-generation
      - name: Prepare the test data
        run: |
          cd experiments
          mkdir -p test/corpus test/model
          cp -irv getuigenverhalen/corpus/GV_Zigma_koopvaardij_08_conversation_clipped test/corpus/
      - name: Generate the model
        run: |
          docker run --volume ${PWD}/model-generation/notebooks:/data/notebooks \
           --volume ${PWD}/experiments/${EXPERIMENT}/corpus:/data/corpus \
           --volume ${PWD}/experiments/${EXPERIMENT}/model:/data/model \
           --user $(id -u):$(id -g) \
           doc2vec
        env:
          EXPERIMENT: test
